/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ErrorLabel {
        "for": string;
        "on": string;
        "type": string;
    }
    interface ErrorLabelGroup {
        "for": string;
        "on": string;
        "template": string;
    }
}
declare global {
    interface HTMLErrorLabelElement extends Components.ErrorLabel, HTMLStencilElement {
    }
    var HTMLErrorLabelElement: {
        prototype: HTMLErrorLabelElement;
        new (): HTMLErrorLabelElement;
    };
    interface HTMLErrorLabelGroupElement extends Components.ErrorLabelGroup, HTMLStencilElement {
    }
    var HTMLErrorLabelGroupElement: {
        prototype: HTMLErrorLabelGroupElement;
        new (): HTMLErrorLabelGroupElement;
    };
    interface HTMLElementTagNameMap {
        "error-label": HTMLErrorLabelElement;
        "error-label-group": HTMLErrorLabelGroupElement;
    }
}
declare namespace LocalJSX {
    interface ErrorLabel {
        "for": string;
        "on"?: string;
        "type": string;
    }
    interface ErrorLabelGroup {
        "for"?: string;
        "on"?: string;
        "template"?: string;
    }
    interface IntrinsicElements {
        "error-label": ErrorLabel;
        "error-label-group": ErrorLabelGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "error-label": LocalJSX.ErrorLabel & JSXBase.HTMLAttributes<HTMLErrorLabelElement>;
            "error-label-group": LocalJSX.ErrorLabelGroup & JSXBase.HTMLAttributes<HTMLErrorLabelGroupElement>;
        }
    }
}
